# Chapter 1, Part 2: Introducing numpy

## Exercise 1

Repeat **Exercise 2** of **Part 1** without using a *for* loop. This time save your result as a numpy array.

### Tips for exercise 1

Python has many packages that will help you perform calculations faster.

One such package is **numpy**. To import numpy and give it the name np write.

In [1]:
import numpy as np

Numpy allows you to transform a list into an array. Arrays can be multiplied the same way that matrices can. You can add two arrays of the same shape, substract them or multiply them by a scalar.

To convert your list $L$ to an array, multiply every element by $2$, and print the result on the notebook write:

In [2]:
L=range(3,10+1)
A=np.array(L)
B=2*A
print B

[ 6  8 10 12 14 16 18 20]


### Write your code here

## Exercise 2

Given the random vector $R$

In [4]:
R=np.random.uniform(0,1,10)

count the number of elements that are greater than $0.5$.

### Tips for exercise 2

You can filter elements from a numpy array using a boolean index. To filter all the elements from $V$ that are greater or equal to $1$ write:

In [5]:
V=np.array([0,1,3,4,0,0,0])
print V
V_filtered=V[V>=1]
print V_filtered

[0 1 3 4 0 0 0]
[1 3 4]


Numpy has many functions to get information out of an array. You can sum all the elements, for example, or you can get the length of the array by doing the following:

In [7]:
V_sum=sum(V)
V_len=len(V)
print V_sum
print V_len

8
7


### Write your code here